name: Build Node

on:
  workflow_dispatch: # 允许手动触发
    inputs:
      node_version:
        description: '要编译的 Node.js 版本 (例如: v20.18.3)'
        required: true
        default: 'v20.18.3' # 默认值，如果用户不输入，就用这个版本
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # 将 NODE_VERSION 和 OUTPUT_FILENAME 与用户输入的值关联起来
      NODE_VERSION: ${{ github.event.inputs.node_version }}
      OUTPUT_FILENAME: node-${{ github.event.inputs.node_version }}-arm64-static

    steps:
      - name: 安装依赖和官方交叉编译工具链
        run: |
          sudo apt-get update
          # 安装官方 aarch64 交叉编译工具链
          sudo apt-get install -y build-essential git-lfs wget gcc-aarch64-linux-gnu g++-aarch64-linux-gnu python3-dev

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: 下载 Node.js 源码
        run: |
          wget https://nodejs.org/dist/${{ env.NODE_VERSION }}/node-${{ env.NODE_VERSION }}.tar.gz
          tar xzf node-${{ env.NODE_VERSION }}.tar.gz

      - name: 设置 Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 交叉编译 Node.js
        working-directory: ${{ github.workspace }}/node-${{ env.NODE_VERSION }}
        run: |
          mkdir ${{ github.workspace }}/node
          ls ${{ github.workspace }}

          # 设置目标平台的交叉编译器
          export CC="aarch64-linux-gnu-gcc"
          export CXX="aarch64-linux-gnu-g++"

          # 运行 configure
          ./configure \
            --dest-cpu=arm64 \
            --fully-static \
            --without-intl \
            --cross-compiling \
            --prefix=${{ github.workspace }}/node

          # 开始编译
          make -j$(nproc)
          make install

      - name: 打包编译结果
        run: |
          tar czf ${{ env.OUTPUT_FILENAME }}.tar.gz -C ${{ github.workspace }} node

      - name: 上传 artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_FILENAME }}
          path: ${{ env.OUTPUT_FILENAME }}.tar.gz
